\context ChordNames \chords {
	% intro
	\skip 1*2

	% Como le cantare al Sennor...
	\break
	\skip 1*4
	\break
	\skip 1*5

	% El esta en los montes y en el mar...
	\break
	\skip 1*6

	% Como le cantare al Sennor...
	\break
	\skip 1*4
	\break
	\skip 1*5

	% No mira en los hombres su color...
	\break
	\skip 1*6

	% Como le cantare al Sennor...
	\break
	\skip 1*4
	\break
	\skip 1*5

	% Vamos a su mesa de bonda...
	\break
	\skip 1*6

	% Como le cantare al Sennor...
	\break
	\skip 1*4
	\break
	\skip 1*5

	% Un mandato nuevo nos da Dios...
	\break
	\skip 1*6

	% Como le cantare al Sennor...
	\break
	\skip 1*4
	\break
	%\skip 1*5
}
