\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		d1 d1

		% estribillo
		d2 g2 a1
		d2 g2 a1
		d2 g2 a1
		d2 a2 d1

		% el esta en los montes y en el mar...
		d1:m
		d1:m c4. d8:m ~ d2:m
		g1:m d1:m
		a1:7 d1

		% estribillo
		d2 g2 a1
		d2 g2 a1
		d2 g2 a1
		d2 a2 d1

		% no mira en los hombres su color...
		d1:m
		d1:m c4. d8:m ~ d2:m
		g1:m d1:m
		a1:7 d1

		% estribillo
		d2 g2 a1
		d2 g2 a1
		d2 g2 a1
		d2 a2 d1

		% vamos a su mesa de bondad...
		d1:m
		d1:m c4. d8:m ~ d2:m
		g1:m d1:m
		a1:7 d1

		% estribillo
		d2 g2 a1
		d2 g2 a1
		d2 g2 a1
		d2 a2 d1

		% un mandato nuevo nos da dios...
		d1:m
		d1:m c4. d8:m ~ d2:m
		g1:m d1:m
		a1:7 d1

		% estribillo
		d2 g2 a1
		d2 g2 a1
		d2 g2 a1
		d2 a2 d1
	}
